apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: assistente-juridico-p

build:
  artifacts:
    - image: assistente-juridico-p
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: /app/src
          - src: 'src/**/*.ts'
            dest: /app/src
          - src: 'src/**/*.css'
            dest: /app/src

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: assistente-juridico-service
    port: 80
    localPort: 8080
