# GitLab CI/CD Pipeline usando Componentes Reutilizáveis
# Assistente Jurídico PJe - Pipeline Completo com Melhores Práticas

# Configuração usando CI/CD Components
include:
  # Componentes de Segurança
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/templates/security/security-component@1.0.0
    inputs:
      stage: security
      audit_level: "standard"
      fail_on_high: true
      report_format: "sarif"

  # Componentes de Testes
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/templates/testing/testing-component@1.0.0
    inputs:
      stage: test
      test_type: "all"
      coverage_threshold: 80
      fail_on_coverage: false
      browser: "chromium"

  # Componentes de Deployment
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/templates/deployment/deployment-component@1.0.0
    inputs:
      stage: deploy
      environment: "staging"
      deploy_target: "vercel"
      health_check_url: "https://assistente-juridico-p.vercel.app"
      rollback_on_failure: true
      monitoring_enabled: true

  # Componentes de Monitoramento
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/templates/monitoring/monitoring-component@1.0.0
    inputs:
      stage: monitor
      monitoring_type: "advanced"
      alert_on_failure: true
      performance_baseline: 3000
      accessibility_threshold: 90

# Configurações globais
stages:
  - security
  - test
  - build
  - deploy
  - monitor

variables:
  NODE_ENV: "production"
  FF_USE_FASTZIP: "true"
  CACHE_COMPRESSION_LEVEL: "fast"
  GIT_DEPTH: 10
  GIT_LFS_SKIP_SMUDGE: "1"
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none

cache:
  key: "npm-cache-v2-${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .npm/

# Job de build personalizado
build:
  stage: build
  image: node:22
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - echo "🔨 Construindo aplicação..."
    - npm run build
    - echo "📦 Build concluído com sucesso"
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  only:
    - merge_requests
    - main
    - develop

# Job de release
release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo "📦 Criando release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG - Assistente Jurídico PJe"
  only:
    - tags
  except:
    - branches

# Job de limpeza
cleanup:
  stage: monitor
  image: alpine:latest
  script:
    - echo "🧹 Executando limpeza..."
    - rm -rf node_modules/.cache || true
    - echo "✅ Limpeza concluída"
  when: always
  allow_failure: true

# Pipeline de produção (apenas para main)
production-deploy:
  extends: build
  stage: deploy
  environment:
    name: production
    url: https://assistente-juridico-p.vercel.app
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - echo "🚀 Deploy para produção executado"
  only:
    - main
  when: manual

# Job de rollback manual
rollback:
  stage: deploy
  image: node:22
  script:
    - echo "🔄 Executando rollback manual..."
    - npx vercel rollback --yes
  environment:
    name: production
    url: https://assistente-juridico-p.vercel.app
  when: manual
  allow_failure: false
  only:
    - main

# Workflow rules para otimização
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        DEPLOY_ENV: "production"
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        DEPLOY_ENV: "staging"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
      variables:
        DEPLOY_ENV: "preview"
    - when: always